version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "fix"
      prefix-development: "chore"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    target-branch: "develop"

    # temporarily disabled until 2024
    open-pull-requests-limit: 5

    commit-message:
      prefix: "ci"
