# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node

# Then, if tests pass, it runs a remote setup script on the configured server over SSH

name: Deploy to server
on:
  workflow_dispatch:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x
          cache: "npm"

      - run: npm ci
      - run: npm run test --maxWorkers=50%
      - run: npm run lint

      - name: Deploy on Server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.KEY }}
          port: ${{ secrets.PORT }}
          script: ${{ secrets.DEPLOY_SCRIPT }}
